import { Language, SettingsState } from "./types";

export const COLORS = {
  white: "#FFFFFF",
  lightGray: "#CCCCCC",
  gray: "#B0B0B0",
  darkGray: "#333333",
  black: "#000000",
};

export const INITIAL_SETTINGS: SettingsState = {
  language: "zh",
  mapMode: "3d",
  showAtc: true,
  bigVideoMode: false,
  hideVideoTitle: false,
  autoCycle: false,
  cycleInterval: 20,
  fullScreen: false,
  largeClock: true,
  hideTopText: false,
  preventTouch: false,
  refreshKey: 0,
};

export const URLS = {
  map3d: "https://objectiveunclear.com/airloom.html?airport=TPE",
  map2d: "https://globe.adsbexchange.com/?lat=25.0797&lon=121.2328&zoom=12",
  chart: "https://ais.caa.gov.tw/eaip/AIRAC%20AIP%20AMDT%2001-26_2026_03_19/documents/Root/Taiwan_Rep/Charts/AD/AD%202%20RCTP/AD%202-24/010-Aerodrome%20Chart.pdf",
  videos: {
    northRunway: "faYmTOvL9qw",
    southRunway: "91PfFoqvuUk",
    northObs: "wWEnxWA7nnY",
    southObs: "y3_x8el5ZJY",
    atc: "NOZVUBsCDEI",
    hyatt: "68GFgzQxrXs",
  },
};

export const MARQUEE_TEXTS = {
  1: ["05L/23R(北跑道)", " 將於 10:30 ~ 11:00 關閉，關閉期間將以 ", "05R/23L(南跑道)", " 進行起降。"],
  2: ["Runway 05L/23R (North Runway)", " will be closed from 10:30 to 11:00 (UTC+8)."],
  3: ["05R/23L(南跑道)", " 將於 11:30 ~ 12:00 關閉，關閉期間將以 ", "05L/23R(北跑道)", " 進行起降。"],
  4: ["Runway 05R/23L (South Runway)", " will be closed from 11:30 to 12:00 (UTC+8)."],
  5: ["目前的跑道運用模式：", "05L/23R(北跑道)", " 主要用於降落，", "05R/23L(南跑道)", " 主要用於起飛。"],
  6: ["Current runway operations: ", "05L/23R (North Runway)", " mainly for arrivals, ", "05R/23L (South Runway)", " mainly for departures."],
  7: ["歡迎來到臺灣桃園國際機場。"],
  8: ["Welcome to Taiwan Taoyuan International Airport."],
};

export const TRANSLATIONS: Record<Language, any> = {
  zh: {
    title: "RCTP-MONITOR",
    done: "完成",
    selectLanguage: "選擇語言",
    map: "地圖",
    live: "即時影像",
    interface: "介面",
    help: "說明",
    mode3d: "3D模式",
    mode2d: "2D模式",
    aerodromeChart: "機場圖",
    largeLiveStream: "大型即時影像",
    hideVideoTitle: "隱藏即時影像標題",
    autoCycle: "輪播即時影像",
    cycleInterval: "輪播間隔",
    seconds: "秒",
    fullScreen: "全螢幕模式",
    largeClock: "大型時鐘",
    hideTopText: "隱藏頂部跑馬燈",
    preventTouch: "防止誤觸",
    configCode: "設定組合代碼",
    copy: "複製",
    apply: "套用",
    refresh: "重新整理",
    northRunway: "北跑道 (North Runway)",
    southRunway: "南跑道 (South Runway)",
    northObs: "北側觀景台 (North Observation Deck)",
    southObs: "南側觀景台 (South Observation Deck)",
    atc: "航空無線電 (ATC)",
    hyatt: "凱悅酒店（W1/W2滑行道）",
    mobileNotice: "此功能無法在行動裝置上使用。",
    instruction: "【RCTP-MONITOR】是一個整合「即時航班動態」、「航空無線電」以及「機場即時影像」的平台，並提供多項自訂功能，讓您能依據自身需求自由調整介面配置、顯示模式與觀看方式，無論是想快速掌握航班資訊，或單純欣賞飛機起降的瞬間，都能獲得更直覺且便利的使用體驗。\n\n機場即時影像來源為「Taoyuan Airport」、「遊桃園 Taoyuan Travel」以及「TWSkyWave 空中電波」之 YouTube 直播頻道；航空無線電來源為「TWSkyWave 空中電波」之 YouTube 直播。若您喜歡這些內容，歡迎前往原頻道訂閱、按讚以支持創作者，讓更多優質的航空觀測資源得以持續經營。\n\n請注意：本平台所呈現之影像、音訊與資訊內容，皆由不同單位或創作者公開提供，其著作權與相關權利均屬原提供者所有，本平台僅基於資訊整合、個人研究與交流分享目的進行整理與展示，並未對原始內容主張任何權利。若相關來源有異動、延遲、中斷、下架、或資訊誤差等情形，皆屬原來源端狀況，本平台將不另行通知，敬請見諒。若您在使用過程中發現問題、錯誤或有任何建議，也歡迎提出回饋，作為後續優化與改進之參考。\n\n另外，本平台絕無任何營利、商業用途或收費行為，純屬個人興趣與自主開發之創作成果。播放即時影像時若出現廣告，其內容、投放方式、顯示頻率與收益分配皆由原提供者及 YouTube 平台機制所設定，與本平台無直接關聯，本平台亦無法控制、介入或自其中獲取任何收益。",
    disclaimer: "1. 本平台所呈現之影像、音訊與資訊內容，皆由不同單位或創作者公開提供，其著作權與相關權利均屬原提供者所有，本平台僅基於資訊整合、個人研究與交流分享目的進行整理與展示，並未對原始內容主張任何權利。若相關來源有異動、延遲、中斷、下架、或資訊誤差等情形，皆屬原來源端狀況，本平台將不另行通知。\n2. 本平台絕無任何營利、商業用途或收費行為，純屬個人興趣與自主開發之創作成果。播放即時影像時若出現廣告，其內容、投放方式、顯示頻率與收益分配皆由原影像提供者及 YouTube 平台機制所設定，與本平台無直接關聯，本平台亦無法控制、介入或自其中獲取任何收益。",
    dontShowAgain: "24小時內不再顯示",
    confirm: "確認",
  },
  en: {
    title: "RCTP-MONITOR",
    done: "Done",
    selectLanguage: "Select Language",
    map: "Map",
    live: "Live Streaming",
    interface: "Interface",
    help: "Directions",
    mode3d: "3D Mode",
    mode2d: "2D Mode",
    aerodromeChart: "Aerodrome Chart",
    largeLiveStream: "Large Live Streaming Player",
    hideVideoTitle: "Hide Live Streaming Title",
    autoCycle: "Auto-cycle Live Streaming",
    cycleInterval: "Cycle Interval",
    seconds: "seconds",
    fullScreen: "Full Screen Mode",
    largeClock: "Large Clock",
    hideTopText: "Hide Top Marquee",
    preventTouch: "Prevent Accidental Touch",
    configCode: "Configuration Code",
    copy: "Copy",
    apply: "Apply",
    refresh: "Refresh",
    northRunway: "North Runway",
    southRunway: "South Runway",
    northObs: "North Observation Deck",
    southObs: "South Observation Deck",
    atc: "ATC Radio",
    hyatt: "Hyatt Hotel (W1/W2 Taxi Way)",
    mobileNotice: "This feature is not available on mobile devices.",
    instruction: "[RCTP-MONITOR] is an integrated platform that combines real-time flight status, aviation radio communications, and live airport camera feeds. It also offers a variety of customization features, allowing you to freely adjust the interface layout, display modes, and viewing preferences according to your needs. Whether you want to quickly check flight information or simply enjoy watching aircraft take off and land, the platform is designed to provide a more intuitive and convenient user experience.\nThe live airport video feeds are sourced from the YouTube livestream channels of “Taoyuan Airport”, “Taoyuan Travel”, and “TWSkyWave Airwaves”. The aviation radio communications are sourced from the YouTube livestream of “TWSkyWave Airwaves”. If you enjoy this content, please consider visiting the original channels to subscribe and like their videos in support of the creators, helping more high-quality aviation observation resources continue to thrive.\nPlease note that all images, audio, and informational content presented on this platform are publicly provided by various organizations or creators. All copyrights and related rights belong to their respective original providers. This platform only organizes and displays such content for the purposes of information integration, personal research, and community sharing, and does not claim any rights to the original materials. If any related sources experience changes, delays, interruptions, removals, or inaccuracies, such circumstances are solely the responsibility of the original providers, and this platform will not issue separate notifications.\nThis platform is strictly non-profit and has no commercial purpose, paid services, or revenue-generating activities of any kind. It is purely a personal project created out of individual interest and independently developed effort. If advertisements appear during the playback of live video streams, their content, delivery methods, display frequency, and revenue distribution are determined entirely by the original video providers and YouTube’s platform mechanisms. They are not directly related to this platform, and this platform has no ability to control, intervene in, or receive any revenue from them.",
    disclaimer: "1. All images, audio, and informational content presented on this platform are publicly provided by various organizations or creators. All copyrights and related rights belong to their respective original providers. This platform only organizes and displays such content for the purposes of information integration, personal research, and community sharing, and does not claim any rights to the original materials. If any related sources experience changes, delays, interruptions, removals, or inaccuracies, such circumstances are solely the responsibility of the original providers, and this platform will not issue separate notifications.\n2. This platform is strictly non-profit and has no commercial purpose, paid services, or revenue-generating activities of any kind. It is purely a personal project created out of individual interest and independently developed effort. If advertisements appear during the playback of live video streams, their content, delivery methods, display frequency, and revenue distribution are determined entirely by the original video providers and YouTube’s platform mechanisms. They are not directly related to this platform, and this platform has no ability to control, intervene in, or receive any revenue from them.",
    dontShowAgain: "Do not show again for 24 hours",
    confirm: "Confirm",
  },
};
